version: 2
jobs:
	build:
		docker:
			- image: circleci/node:4.8.2
		steps:
			- checkout
			- run:
				command: npm install -g grunt-cli
				name: Install Grunt CLI globally
			- run:
				command: npm install
				name: Install NPM packages
			- run:
				command: grunt build
				name: Run Grunt build
