version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run:
        name: `npm install -g grunt-cli`
        command: npm install -g grunt-cli
      - run:
        name: `npm install`
        command: npm install
      - run:
        name: `grunt build`
        command: grunt build
